title : Vriksha
description: 'A blog about Chemical Reaction Networks, Machine Learning and Category Theory.'

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
plugins: [jekyll-gist]
plugins: [jekyll-paginate]
permalink: /:year/:month/:title.html
